---
title: "Causes of Deaths"
author: "Deon Vasquez, Ben Ramirez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing all libraries

```{r}
library("janitor")
library("tidyverse")
library("shiny")
library("shinydashboard")
options(scipen=999)
```
##Loading Data
```{r}
cause_of_death <- read_csv("data/death/cause_of_deaths.csv") %>% clean_names()


```
##Little bit of cleaning to make a happy coder
```{r}
cause_of_death_country <- rename(cause_of_death, country = "country_territory")
cause_of_death_country
```

##Looking at Data Structure
```{r}
glimpse(cause_of_death_country)
```


##Sorting out Non-infectious or Irrelevant modes of death to Travelers.
```{r}
names(cause_of_death_country)
sorted_cause_of_death <- cause_of_death_country%>% 
  select(-c( meningitis, alzheimers_disease_and_other_dementias, parkinsons_disease, nutritional_deficiencies,maternal_disorders, cardiovascular_diseases, neonatal_disorders, self_harm, neoplasms, diabetes_mellitus, chronic_kidney_disease, chronic_respiratory_diseases, cirrhosis_and_other_chronic_liver_diseases,acute_hepatitis))
sorted_cause_of_death
```

##Elongating Data
```{r}
longer_cause_of_death <- sorted_cause_of_death %>%  
  pivot_longer(-c("country","code","year"), 
               names_to = "cause_of_death",
               values_to = "deaths")
longer_cause_of_death
```
##A Little More Cleaning
```{r}
longer_cause_of_death_clean <- longer_cause_of_death %>% 
  rename( year = "year", country_code = "code")
longer_cause_of_death_clean
```

##Selecting Countries of Interest(Asia)/Selecting popular tourist countries in Asia
```{r}
tourist_countries_asia_death <- longer_cause_of_death_clean %>% 
  filter(country_code %in% c("THA","VNM","JPN","IND","IDN","CHN","KHM", "PHL", "MDV","KOR","MYS","MMR","LAO","SGP", "BGD"))
tourist_countries_asia_death
```
##Sorting into more recent years (2010 and on)
```{r}
modern_cause_of_death <- tourist_countries_asia_death%>% 
filter(year>= 2010)
modern_cause_of_death
```

```{r}


ui <- dashboardPage(
  dashboardHeader(title = "Death in Asia"),
  dashboardSidebar(disable=T),
  dashboardBody(
     fluidRow(
    box(title = "Plot Settings", width =3,   
    selectInput("x", "Select Country", choices = c("Bangladesh", "Cambodia","China","India","Indonesia","Japan","Laos","Malaysia","Maldives","Myanmar","Philippines","Singapore","South Korea","Thailand", "Vietnam"), selected = "Cambodia"),
    selectInput("y", "Select Cause of Death", choices = c("alcohol_use_disorders","diarrheal_diseases","drowning","drug_use_disorders","exposure_to_forces_of_nature","hiv_aids","interpersonal_violence","lower_respiratory_infections","malaria","tuberculosis","environmental_heat_and_cold_exposure","conflict_and_terrorism","poisonings	","protein_energy_malnutrition","road_injuries","digestive_diseases","fire_heat_and_hot_substances"), selected = "alcohol_use_disorders" )
  )
  ),
  box(plotOutput("plot", width = "500px", height = "400px")
)
)
)
server <- function(input, output, session) {
  output$plot <- renderPlot({
    modern_cause_of_death %>% 
      filter(country == input$x) %>% 
      filter(cause_of_death==input$y) %>% 
      mutate(year = as_factor(year)) %>% 
      ggplot(aes(x=year, y=deaths, fill=year))+geom_col()+labs(title = "Number of Deaths by Cause per Year from 2010-2019", x= "Year 2010-2019", y="Number of Deaths", fill = "Year")
  })
  session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```

```{r}


ui <- dashboardPage(
  dashboardHeader(title = "Death by Asian Country"),
  dashboardSidebar(disable=T),
  dashboardBody(
       
    selectInput("x", "Select Country", choices = c("Bangladesh", "Cambodia","China","India","Indonesia","Japan","Laos","Malaysia","Maldives","Myanmar","Philippines","Singapore","South Korea","Thailand", "Vietnam"), selected = "Thailand"),
  plotOutput("plot", width = "500px", height = "400px")

)
)
server <- function(input, output, session) {
  output$plot <- renderPlot({
    modern_cause_of_death %>% 
      
     filter(country == input$x) %>% 
  ggplot(aes(x=year, y= deaths, color = cause_of_death))+
  geom_line()+labs(title = "Deaths yearly sorted by Cause per Country", x= "Year 2010-2019", y="Number of Deaths", color = "Cause of Death")
  })
  session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Deaths in Asia by Year"),
  dashboardSidebar(disable=T),
  dashboardBody(
    fluidRow(
      box(title = "Plot Settings",width = 3,
            selectInput("y", "Select Year", choices = c("2010","2011","2012","2013","2014","2015","2016","2017", "2018", "2019"), selected = "2010"),
          selectInput("x", "Select Country", choices = c("Bangladesh", "Cambodia","China","India","Indonesia","Japan","Laos","Malaysia","Maldives","Myanmar","Philippines","Singapore","South Korea","Thailand", "Vietnam"), selected = "Thailand"),
          plotOutput("plot", width = "500px", height = "400px")))))
server <- function(input, output, session) {
  output$plot <- renderPlot({
    modern_cause_of_death %>% 
      filter(year== input$y) %>% 
      filter(country== input$x) %>% 
      ggplot(aes(x=cause_of_death, y= deaths, fill=cause_of_death))+geom_col()+theme(axis.text.x =)+labs(title = "Deaths in Asia Sorted by Country and Year", x= "Cause of Death", y="Number of Deaths", fill = "Cause of Death")+ theme(axis.text.x = element_blank(), axis.ticks = element_blank())
  })
        session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```

