---
title: "Causes of Deaths"
author: "Deon Vasquez, Ben Ramirez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing all libraries

```{r}
library("janitor")
library("tidyverse")
library("shiny")
library("shinydashboard")
library("janitor")
```
# Importing data
```{r}
deaths <- readr::read_csv("data/cause_of_deaths.csv")
deaths
```
```{r}
names(deaths)
```

# Cleaning names
```{r}
clean_names_deaths <- janitor::clean_names(deaths)
```
```{r}
names(clean_names_deaths)
```
```{r}
clean_names_deaths_long <- clean_names_deaths %>% 
  pivot_longer(-c("country_territory", "code", "year"),
               names_to = "causes",
               values_to = "deaths")
```

# Limiting Cause of Deaths

```{r}
names(clean_names_deaths)
```


```{r}
short_deaths_long <- clean_names_deaths_long %>% 
  filter(causes %in% c("country_territory", "code", "year", "malaria", "drowning", "interpersonal_violence", "hiv_aids", "tuberculosis","alcohol_use_disorders","exposure_to_forces_of_nature","diarrheal_diseases", "environmental_heat_and_cold_exposure", "conflict_and_terrorism", "poisonings", "protein_energy_malnutrition", "road_injuries", "digestive_diseases", "digestive_diseases"))
```


# Limiting to South America

```{r}
south_america <- short_deaths_long %>% 
  filter(country_territory %in% c("Venezuela", "Colombia", "Ecuador", "Peru", "Chile", "Argentina", "Uruguay", "Paraguay", "Bolivia", "Brazil", "Suriname", "Guyana"))
```

```{r}
summary(south_america)
```


```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Causes of Deaths by Country"),
  dashboardSidebar(disable = T),
  dashboardBody(
    fluidRow(
      box(title = "Plot Options", width = 3,
          selectInput("cause", "Select Cause of Death", choices = south_america$causes, 
                      selected = "malaria"),
          selectInput("year", "Select Range of Year (1990 - 2019)", choices = south_america$year),
      ),
       box(plotOutput("plot", width = "500px", height = "500px")
      )
    ),
    fluidRow(
      box(title = "Plot Options", width = 3,
          selectInput("cause", "Select Cause of Death", choices = south_america$causes, 
                      selected = "malaria"),
          selectInput("country", "Select Country", choices = south_america$country_territory),
      ),
       box(plotOutput("plot2", width = "500px", height = "500px")
      )
    )
  )
)

server <- function(input, output, session) {
  
  output$plot <- renderPlot({
    
    south_america %>% 
      filter(causes == input$cause) %>% # user selects death type
      filter(year == input$year) %>% # user selects year
      ggplot(aes(x= country_territory, y= deaths, fill = country_territory))+ 
        geom_col()
      
  })
  
  output$plot2 <- renderPlot({
    
    south_america %>% 
  filter(country_territory == input$country) %>% 
  filter(causes == input$cause) %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(x=year, y= deaths))+
  geom_col()
    
  })
  
  session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```


```{r}
south_america %>% 
  pivot_wider(names_from = causes, values_from = deaths) %>% 
  filter(year == 2019) %>% 
  ggplot(aes(x= country_territory, y= "tuberculosis"))+
  geom_col()
```

```{r}
south_america %>% 
      filter(causes == "malaria") %>% 
      pivot_wider(names_from = causes, values_from = deaths) %>% 
      filter(year == 2019) %>% 
      ggplot(aes(x= country_territory, y= malaria, fill= country_territory))+
        geom_col()
```

```{r}
south_america %>% 
  filter(country_territory == "Brazil") %>% 
  ggplot(aes(x=year, y= deaths, color = causes))+
  geom_line() 
```

```{r}
south_america %>% 
  filter(country_territory == "Brazil") %>% 
  pivot_wider(names_from = causes, values_from = deaths) %>%
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(x=year, y= malaria))+
  geom_col()
```

```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Causes of Deaths by Country"),
  dashboardSidebar(disable = F),
  dashboardBody(
    fluidRow(
      box(title = "Plot Options", width = 3,
          selectInput("cause", "Select Cause of Death", choices = south_america$causes, 
                      selected = "malaria"),
          selectInput("country", "Select Country", choices = south_america$country_territory),
      ),
       box(plotOutput("plot2", width = "500px", height = "500px")
      )
    )
  )
)

server <- function(input, output, session) {
  
  output$plot2 <- renderPlot({
    
    south_america %>% 
  filter(country_territory == input$country) %>% 
  filter(causes == input$cause) %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(x=year, y= deaths))+
  geom_col()
    
  })
  
  session$onSessionEnded(stopApp)
}

shinyApp(ui, server)
```



```{r}
south_america %>% 
  filter(country_territory == "Venezuela
         ") %>% 
  pivot_wider(names_from = causes, values_from = deaths) %>%
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(x=year, y= malaria))+
  geom_col()
```


```{r}
south_america %>% 
  filter(year >= 1990) %>% 
  filter(year <= 2005) %>% 
  
```


```{r}
library(shiny)

ui <- dashboardBody(
    fluidRow(
      box(title = "Plot Options", width = 3,
          selectInput("cause", "Select Cause of Death", choices = south_america$causes, 
                      selected = "malaria"),
          selectInput("country", "Select Country", choices = south_america$country_territory),
      ),
       box(plotOutput("plot2", width = "500px", height = "500px")
       )
    )
)

server <- function(input, output, session) {
  
    output$plot2 <- renderPlot({
    
    south_america %>% 
  filter(country_territory == input$country) %>% 
  filter(causes == input$cause) %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(x=year, y= deaths))+
  geom_col()
    
  })
  
  session$onSessionEnded(stopApp)

}

shinyApp(ui, server)
```

